name: soccer-rag
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python version
  - python=3.10
  
  # Core scientific computing
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  
  # PyTorch ecosystem
  - pytorch>=2.0.0
  - pytorch-cpu
  - torchvision
  - torchaudio
  
  # Development tools
  - pip
  - jupyter
  - ipykernel
  - git
  
  # System dependencies
  - libffi
  - openssl
  
  # Pip dependencies
  - pip:
      # Sentence transformers and embeddings
      - sentence-transformers>=2.2.0
      - transformers>=4.30.0
      - tokenizers>=0.13.0
      
      # Google AI
      - google-generativeai>=0.3.0
      
      # Vector search
      - faiss-cpu>=1.7.4
      - annoy>=1.17.0
      
      # Utilities
      - tqdm>=4.65.0
      - click>=8.1.0
      - typing-extensions>=4.5.0
      - pathlib2>=2.3.7
      - json5>=0.9.0
      
      # Development and testing
      - pytest>=7.4.0
      - pytest-cov>=4.1.0
      - black>=23.0.0
      - flake8>=6.0.0
      
      # Optional: Web API
      - fastapi>=0.100.0
      - uvicorn>=0.23.0
      - pydantic>=2.0.0
      
      # Optional: Visualization
      - matplotlib>=3.7.0
      - seaborn>=0.12.0
      - plotly>=5.15.0